trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**\*Tests.csproj'
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\SecondaryTests.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
